# -*- coding: utf-8 -*-
"""Lambda_Function_Test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1orPudQGaId3I9MVc9yPcH5y9_LposMyi
"""

import psycopg2 as ps
import requests
import json

POSTGRES_ADDRESS = "FILL" ## End Point
POSTGRES_PORT = 'FILL' ##Port #
POSTGRES_USERNAME = 'FILL' ## CHANGE THIS TO YOUR PANOPLY/POSTGRES USERNAME
POSTGRES_PASSWORD = 'FILL' ## CHANGE THIS TO YOUR PANOPLY/POSTGRES PASSWORD 
POSTGRES_DBNAME = 'FILL' ## CHANGE THIS TO YOUR DATABASE NAME
# A long string that contains the necessary Postgres login information 
postgres_str = ('postgresql://{username}:{password}@{ipaddress}:{port}/{dbname}'.format(username=POSTGRES_USERNAME, password=POSTGRES_PASSWORD, ipaddress=POSTGRES_ADDRESS,port=POSTGRES_PORT, dbname=POSTGRES_DBNAME))

def insertdata(table_name):
    test_data = [8433833, 0.02199, 1.47195622, 2019-10, 0.08199, 0.02991, 8578.16380674]
    # Connect to database.
    conn = ps.connect(host=POSTGRES_ADDRESS,database=POSTGRES_DBNAME,user=POSTGRES_USERNAME,password=POSTGRES_PASSWORD,port=POSTGRES_PORT)
    
    # Create a cursor.
    cur = conn.cursor()
    
    # Insert row into table.
    insert_query = "INSERT INTO {} (trade_id, price, size, time, bid, ask, volume) VALUES (%s, %s, %s, %s, %s, %s, %s)".format(table_name)  
    cur.execute(insert_query, test_data)
    
    # Commit and close.
    conn.commit()
    cur.close()

def lambda_handler(event, context):
    table_name = 'crypto_data.eth_btc_coinbase'
    print(table_name)
    insertdata(table_name)
    return 'Successful!'