# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G0whEr56Cd8VwlW5Cjx6vX1gCVChoEyU
"""

def add_btc_closing_price_column(filename):
    
    """ Function that merges the price column of btc in terms of USD to the all other CSVs per exchange"""\
    
    # State paths for each exchange file that cointains the price of bitcoin in terms of USD.
        
    path_bitfinex = 'bitfinex_btc_usd_300.csv'
    path_coinbase_pro = 'coinbase_pro_btc_usd_300.csv'
    path_hitbtc = 'hitbtc_btc_usdt_300.csv'

    # Conditional for reading the right exchange's CSV.
    
    if exchange == 'bitfinex':

        df1 = pd.read_csv(path_bitfinex, index_col=0)

    elif exchange == 'coinbase_pro':

        df1 = pd.read_csv(path_coinbase_pro, index_col=0)
        
    elif exchange == 'hitbtc':
        
        df1 = pd.read_csv(path_hitbtc, index_col=0)

    # Create a separate dataframe of just closing_time and close.
    df2 = df1[['closing_time','close']]
    
    # Rename columns.
    df2.columns = ['closing_time','close_btc']
    
    # Create a dictionary.
    df_dict = {}
        
       
    # Looping through all files to execute merging.
    for filename in os.listdir():
        if filename.endswith('btc_300.csv'):
            
                # Selecting dataframe to merge.
                df_to_merge = pd.read_csv(filename, index_col=0)
                
                # Merging dataframe and column on 'closing_time'.
                df_merged = df_to_merge.merge(df2, on='closing_time')
    
                # Fill Nan after merged.
                df_merged2 = df_merged.fillna(method='bfill')
                
                # Calls filename for the selected pair.
                df_dict[filename] = df_merged2
                
    add_column = pd.DataFrame.from_dict(df_dict)
                    
    return add_column

# This function needs to be adapted so that it can be called on the feature_engineering function, 
# so that the dataframe gets merged with the price column of btc depending on the exchange.